traiterJson({
"numDiag":1,
"notes":"heh",
"trait":105,
"scoreJ":0,
"scoreJ5":0,
"scoreR":24,
"scoreR5":0,
"bonusJ":0,
"malusJ":0,
"bonusR":0,
"malusR":0,
"cols":[
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":1, "couleur":1},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":1, "couleur":2},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":63},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":-96},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":104},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":-31},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
]
});